apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/your-user/your-gitops-repo.git # change me
